server:
  port: 8081

spring:
  application:
    name: common-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tlh-common
    username: postgres
    password: 14052003

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    hibernate:
      ddl-auto: create
  kafka:
    bootstrap-servers: http://localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

topic:
  name: simple.mail.topic

jwt:
  access:
    secret: SECRET
token:
  lifetime:
    in:
      minutes: 60000