server:
  port: 8765

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
#        - id: user-service
#          uri: http://localhost:8080
#          predicates:
#            - Path=/user/**
        - id: common-service
          uri: http://localhost:8081
          predicates:
            - Path=/common/**